AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api-taxreturns

  Sample SAM Template for api-taxreturns
Parameters:
  Stage:
    Type: String
    Description: The stage of the application (e.g., dev, staging, prod)

Resources:
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: LambdaS3DynamoDBAccessPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                  - s3:GetObject
                  - s3:PutObject
                Resource: 
                  - !Sub "arn:aws:s3:::taxreturns-frontend-storage-73711795134329-${Stage}/*"
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource: 
                  - !Sub "arn:aws:dynamodb:us-east-1:848638426587:table/TaxReturns-${Stage}"

  TaxReturn:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: taxreturns/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Role: !GetAtt LambdaExecutionRole.Arn


  TaxReturnGeneratePDF:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: taxreturns/
      Handler: app.lambda_handler
      Runtime: python3.9
      Architectures:
      - x86_64
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get
      Role: !GetAtt LambdaExecutionRole.Arn
